Repository aeecleclair/Siarnaq, pull requests merged in 2024-08, with the labels that each got.

#40 Change url to rentree.myecl.fr
  .github/workflows/deploy.yml
Labels: enhancement

#41 feat: plausible analytics
  src/app/layout.tsx
Labels: enhancement

#55 feat: add remaining to pay
  src/components/user/RecapPanel.tsx
  src/translations/en.json
  src/translations/fr.json
Labels: enhancement

#56 feat: use an ellipsis icon for sellers without purchases and use HeroIcons 2
  src/components/admin/adminPanel/CurriculumAccordion/CurriculumItem.tsx
  src/components/admin/adminPanel/RecapPanel/RecapPanel.tsx
  src/components/admin/adminPanel/SellerAccordion.tsx/ToggleSeller.tsx
  src/components/admin/sellerProducts/AddProductAccordionItem.tsx
  src/components/admin/userSearch/DataTableRowActions.tsx
  src/components/custom/Payment/PaymentItem.tsx
  src/components/custom/Payment/PaymentPart.tsx
  src/components/custom/Product/PurchaseItem.tsx
  src/components/custom/StatusDialog.tsx
  src/components/custom/VariantCard.tsx
  src/components/custom/productAccordion/AddingVariantCard.tsx
  src/components/user/AssociationPanel.tsx
Labels: enhancement

#58 fix: put Quantity and Seller Name in two span
  src/components/custom/Product/PurchaseItem.tsx
Labels: enhancement

#57 feat: sort imports using prettier-plugin-sort-imports
  .prettierrc
  src/api/services.gen.ts
  src/app/admin/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/queryProvider.tsx
  src/components/admin/adminPanel/AdminPanel.tsx
  src/components/admin/adminPanel/CurriculumAccordion/CurriculumAccordionItem.tsx
  src/components/admin/adminPanel/RecapPanel/RecapPanel.tsx
  src/components/admin/adminPanel/SellerAccordion.tsx/SellerAccordionItem.tsx
  src/components/admin/sellerProducts/AddProductAccordionItem.tsx
  src/components/admin/sellerProducts/SellerTab.tsx
  src/components/admin/sellerProducts/SellerTabContent.tsx
  src/components/admin/sellerProducts/SellerTabContentList.tsx
  src/components/admin/userSearch/Columns.tsx
  src/components/admin/userSearch/DataTable.tsx
  src/components/admin/userSearch/DataTableToolbar.tsx
  src/components/admin/userSearch/UserSearch.tsx
  src/components/admin/userSearch/searchFunction.ts
  src/components/custom/CustomDialog.tsx
  src/components/custom/DatePicker.tsx
  src/components/custom/HelloAssoButton.tsx
  src/components/custom/MultiSelect.tsx
  src/components/custom/Payment/PaymentItem.tsx
  src/components/custom/Payment/PaymentPart.tsx
  src/components/custom/Product/ProductPart.tsx
  src/components/custom/Product/PurchaseItem.tsx
  src/components/custom/StatusDialog.tsx
  src/components/custom/StyledFormField.tsx
  src/components/custom/VariantCard.tsx
  src/components/custom/WarningDialog.tsx
  src/components/custom/productAccordion/AddEditVariantForm.tsx
  src/components/custom/productAccordion/AddingVariantCard.tsx
  src/components/custom/productAccordion/ProductAccordion.tsx
  src/components/custom/productAccordion/ProductAccordionOptions.tsx
  src/components/custom/productAccordion/VariantCardOptions.tsx
  src/components/custom/productAccordion/VariantCardWithOptions.tsx
  src/components/login/MyECLButton.tsx
  src/components/user/CentralPanel.tsx
  src/components/user/IntroCarouselItems.tsx
  src/components/user/IntroPanel.tsx
  src/components/user/PaymentButton.tsx
  src/components/user/ProductPanel.tsx
  src/components/user/RecapPanel.tsx
  src/hooks/useCoreUser.ts
  src/hooks/useCurriculums.ts
  src/hooks/useGroups.ts
  src/hooks/useOnlineSellerProducts.ts
  src/hooks/useOnlineSellers.ts
  src/hooks/useProducts.ts
  src/hooks/useSellerProducts.ts
  src/hooks/useSellers.ts
  src/hooks/useStatus.ts
  src/hooks/useUser.ts
  src/hooks/useUserMemberships.ts
  src/hooks/useUserPayments.ts
  src/hooks/useUserPurchases.ts
  src/hooks/useUserSellerPurchases.ts
  src/hooks/useUsers.ts
Labels: enhancement

#65 Fix/post pay url
  src/api/schemas.gen.ts
  src/api/services.gen.ts
  src/api/types.gen.ts
  src/hooks/usePaymentUrl.ts
Labels: bug

#67 Add page indicator for info and recap
  src/components/custom/PageIndicator.tsx
  src/components/user/CentralPanel.tsx
  src/components/user/InfoPanel.tsx
  src/components/user/ProductPanel.tsx
  src/components/user/RecapPanel.tsx
  src/translations/fr.json
Labels: enhancement

#73 fix: add missing register url slash
  src/app/login/page.tsx
Labels: bug

#76 fix: set open accordion items only when there are products available
  src/components/admin/adminPanel/AdminPanel.tsx
  src/components/admin/sellerProducts/SellerTabContent.tsx
  src/components/user/ProductPanel.tsx
Labels: bug

#74 fix: responsive recap
  src/components/custom/Payment/PaymentItem.tsx
  src/components/custom/Product/PurchaseItem.tsx
  src/components/custom/productAccordion/ProductAccordion.tsx
Labels: bug, online

#78 feat: unpinning when unselecting
  src/components/admin/userSearch/DataTable.tsx
Labels: bug, onsite, admin

#80 Add English translation and wording improvements
  src/components/user/InfoPanel.tsx
  src/translations/en.json
  src/translations/fr.json
Labels: bug, online

#91 Allow to select all cursus when creating/updating variants
  package.json
  src/components/custom/MultiSelect.tsx
  src/components/ui/scroll-area.tsx
  yarn.lock
Labels: enhancement, onsite

#94 feat: show recap on online mode for cdradmin
  src/components/admin/sellerProducts/SellerTabList.tsx
Labels: enhancement

#97 Feat/add curriculum
  src/components/admin/sellerProducts/SellerTabList.tsx
  src/components/admin/userSearch/DataTableToolbar.tsx
  src/components/custom/User/AddUserWithCurriculum.tsx
  src/components/custom/VariantCard.tsx
Labels: onsite, admin
